# Generated by Django 4.1.7 on 2023-03-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Марка')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('rudder_location', models.CharField(max_length=100, verbose_name='Расположение руля')),
                ('engine_volume', models.PositiveSmallIntegerField(max_length=100, verbose_name='Обьем двигателя')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
