# Generated by Django 4.1.7 on 2023-03-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.PositiveSmallIntegerField(verbose_name='Обьем двигателя'),
        ),
    ]
