# Generated by Django 4.1.7 on 2023-04-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_year_alter_car_engine_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Гос.номер'),
        ),
    ]
