# Generated by Django 4.1.7 on 2023-04-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_specialmarks_periodsownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodsownership',
            name='actual',
        ),
        migrations.AlterField(
            model_name='periodsownership',
            name='before_date',
            field=models.DateField(blank=True, null=True, verbose_name='До'),
        ),
    ]
